export { default as Calendario } from './Calendario';
export { default as Campeonatos } from './Campeonatos';
export { default as ComissaoTecnica } from './ComissaoTecnica';
export { default as Elenco } from './Elenco';
export { default as Home } from './Home';
export { default as MeuPerfil } from './MeuPerfil';
export { default as Sumulas } from './Sumulas';
export { default as Login} from './Login';
export { default as Signup } from './Signup';
export { default as CampeonatoDetalhes } from './CampeonatoDetalhes';
export { default as Transferencias } from './Transferencias';
export { default as Clubes } from './Clubes';
export { default as SumulasDetalhes } from './SumulasDetalhes';
export { default as Campos } from './Campos';
export { default as ControleAtletas } from './ControleAtletas';
export { default as Documentos } from './Documentos';
export { default as Estatísticas } from './Estatísticas';
