export { default as Calendario } from './Calendario';
export { default as Campeonatos } from './Campeonatos';
export { default as ComissaoTecnica } from './ComissaoTecnica';
export { default as Elenco } from './Elenco';
export { default as Home } from './Home';
export { default as MeuPerfil } from './MeuPerfil';
export { default as Tarefas } from './Tarefas';
export { default as Login} from './Login';
export { default as Signup } from './Signup';
export { default as CampeonatoDetalhes } from './CampeonatoDetalhes';